apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-cd-
  namespace: argo
spec:
  serviceAccountName: argo-workflow
  entrypoint: deploy

  templates:
  - name: deploy
    container:
      image: bitnami/kubectl:latest
      command: [sh, -c]
      args:
        - |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ci-cd
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: ci-cd
            template:
              metadata:
                labels:
                  app: ci-cd
              spec:
                containers:
                - name: app
                  image: sonalmallah12/ci-cd:latest
          EOF

