apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
      - name: app
        image: sonalmallah12/ci-cd:latest

